//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeProducts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logined
    {
        public int LoginedID { get; set; }
        public string UserLogin { get; set; }
        public string UserPassword { get; set; }
        public int UserRoleID { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}
